module.exports = [
  {
  id:1,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},{
  id:2,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},{
  id:3,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},{
  id:4,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},{
  id:5,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},{
  id:6,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
{
  id:7,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
{
  id:8,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
{
  id:9,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
{
  id:10,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
{
  id:11,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
{
  id:12,
  name: 'PARAGLIDING' ,
  difficulty: 'Extreme',
  duration: 5,
  season:'Summer',
},
]